defaults:
  - datasets: data
  - models: model
  - experiments: exp
  - _self_

seed: 42

hydra:
  job_logging:
    version: 1
    root:
      level: INFO
      handlers: [console, file]
  hydra_logging:
    level: INFO

results:
  save_path: "reports/"
